package cn.iocoder.yudao.module.cloudmold.risk.api;

public enum RiskOperation {
    CREATE_POLICY,
    PUBLISH_POLICY_VERSION,
    CREATE_INTELLIGENCE_EVENT_TAXONOMY,
    PUBLISH_INTELLIGENCE_EVENT_TAXONOMY_VERSION,
    RETIRE_INTELLIGENCE_EVENT_TAXONOMY,
    DETECT_SIGNAL,
    OBSERVE_RELATIONSHIP,
    CREATE_CLUSTER,
    ADD_CLUSTER_MEMBER,
    CHANGE_CLUSTER_STATUS,
    OPEN_REVIEW,
    START_REVIEW,
    DECIDE_REVIEW,
    CLOSE_REVIEW,
    RECORD_FEEDBACK,
    LINK_ORDER_REVIEW_CASE,
    OPEN_PAYMENT_DISPUTE,
    RESOLVE_PAYMENT_DISPUTE,
    POST_LOSS_ENTRY
}
