package cn.iocoder.yudao.module.cloudmold.gamification.api;

public enum GamificationOperation {
    CREATE_GAME,
    PUBLISH_GAME_VERSION,
    OPEN_PLAYER_ACCOUNT,
    OPEN_SESSION,
    START_ROUND,
    COMPLETE_ROUND,
    DEFINE_REWARD,
    DEFINE_DRAW_POOL,
    GRANT_REWARD,
    DRAW,
    RECORD_ASSIST,
    DEFINE_TASK,
    ADVANCE_TASK,
    TRANSFER_GIFT,
    DEFINE_SEASON_SERIES,
    DEFINE_SEASON,
    DEFINE_COLLECTIBLE,
    GRANT_COLLECTIBLE,
    CREATE_REDEMPTION_INTENT,
    RECORD_REDEMPTION_RESULT,
    CREATE_REWARD_CLAIM,
    CLAIM_REWARD,
    EXPIRE_REWARD_CLAIM
}
