CREATE TABLE IF NOT EXISTS cloudmold_event_outbox (
  event_id varchar(36) NOT NULL,
  event_type varchar(128) NOT NULL,
  schema_version int NOT NULL,
  source_system varchar(64) NOT NULL,
  tenant_id bigint NOT NULL,
  aggregate_type varchar(64) NOT NULL,
  aggregate_id varchar(128) NOT NULL,
  aggregate_version bigint NOT NULL,
  event_sequence smallint NOT NULL DEFAULT 1,
  occurred_at timestamp NOT NULL,
  recorded_at timestamp NOT NULL,
  trace_id varchar(64),
  correlation_id varchar(36) NOT NULL,
  causation_id varchar(36),
  idempotency_key varchar(200) NOT NULL,
  payload varchar(4000) NOT NULL,
  headers varchar(4000),
  payload_hash char(64) NOT NULL,
  destination varchar(128) NOT NULL,
  status tinyint NOT NULL DEFAULT 0,
  available_at timestamp NOT NULL,
  attempt_count int NOT NULL DEFAULT 0,
  max_attempts int NOT NULL DEFAULT 20,
  lease_owner varchar(128),
  lease_until timestamp,
  published_at timestamp,
  last_error_code varchar(64),
  last_error_summary varchar(512),
  PRIMARY KEY (event_id),
  UNIQUE (tenant_id, aggregate_type, aggregate_id, aggregate_version, event_sequence),
  UNIQUE (tenant_id, event_type, idempotency_key)
);

CREATE TABLE IF NOT EXISTS cloudmold_event_inbox (
  consumer_id varchar(128) NOT NULL,
  event_id varchar(36) NOT NULL,
  tenant_id bigint NOT NULL,
  event_type varchar(128) NOT NULL,
  schema_version int NOT NULL,
  payload_hash char(64) NOT NULL,
  processed_at timestamp NOT NULL,
  result_hash char(64),
  PRIMARY KEY (consumer_id, event_id)
);
