CREATE TABLE cloudmold_ai_ops_workflow_evidence_operation (
    operation_id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    attempt_token VARCHAR(36) NOT NULL,
    status TINYINT NOT NULL,
    aggregate_type VARCHAR(32) NULL,
    aggregate_id VARCHAR(64) NULL,
    result_json MEDIUMTEXT NULL,
    created_by VARCHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (operation_id),
    UNIQUE KEY uk_ai_ops_wf_evidence_op_tenant_idem (tenant_id, operation_type, idempotency_key),
    CONSTRAINT ck_ai_ops_wf_evidence_op_status CHECK (status IN (0, 10))
);

CREATE TABLE cloudmold_ai_ops_workflow_observation (
    observation_id VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    lineage_id VARCHAR(128) NOT NULL,
    workflow_id VARCHAR(191) NOT NULL,
    workflow_version VARCHAR(64) NOT NULL,
    proposal_id VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    headline VARCHAR(191) NOT NULL,
    detail_text TEXT NOT NULL,
    evidence_ref VARCHAR(255) NULL,
    summary_source_refs_json JSON NULL,
    model_summary TEXT NULL,
    metrics_json JSON NULL,
    severity VARCHAR(16) NOT NULL,
    dqc_status VARCHAR(32) NOT NULL,
    record_status VARCHAR(32) NOT NULL,
    release_eligible TINYINT(1) NOT NULL DEFAULT 0,
    corroborating_source_types_json JSON NULL,
    fresh_until DATETIME(6) NULL,
    window_start DATETIME(6) NOT NULL,
    window_end DATETIME(6) NOT NULL,
    observed_at DATETIME(6) NOT NULL,
    actor_subject VARCHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (observation_id),
    KEY idx_ai_ops_wf_obs_tenant_workflow_window (tenant_id, workflow_id, window_start, window_end),
    CONSTRAINT ck_ai_ops_wf_obs_source_type CHECK (source_type IN ('USER_BEHAVIOR', 'SYSTEM_RUN', 'SYSTEM_LOG', 'BUSINESS_KPI', 'DQC', 'APPROVAL', 'WORK_ORDER', 'EXTERNAL_WEB')),
    CONSTRAINT ck_ai_ops_wf_obs_severity CHECK (severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_ai_ops_wf_obs_dqc CHECK (dqc_status IN ('PASS', 'WARN', 'FAIL', 'UNKNOWN', 'NOT_APPLICABLE')),
    CONSTRAINT ck_ai_ops_wf_obs_status CHECK (record_status IN ('CAPTURED', 'CONFIRMED', 'STALE', 'REJECTED')),
    CONSTRAINT ck_ai_ops_wf_obs_window CHECK (window_end >= window_start),
    CONSTRAINT ck_ai_ops_wf_obs_fresh CHECK (fresh_until IS NULL OR fresh_until >= window_end)
);

CREATE TABLE cloudmold_ai_ops_workflow_problem (
    problem_id VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    lineage_id VARCHAR(128) NOT NULL,
    workflow_id VARCHAR(191) NOT NULL,
    workflow_version VARCHAR(64) NOT NULL,
    proposal_id VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    headline VARCHAR(191) NOT NULL,
    problem_detail TEXT NOT NULL,
    evidence_ref VARCHAR(255) NULL,
    summary_source_refs_json JSON NULL,
    model_summary TEXT NULL,
    metrics_json JSON NULL,
    severity VARCHAR(16) NOT NULL,
    dqc_status VARCHAR(32) NOT NULL,
    record_status VARCHAR(32) NOT NULL,
    release_eligible TINYINT(1) NOT NULL DEFAULT 0,
    corroborating_source_types_json JSON NULL,
    fresh_until DATETIME(6) NULL,
    window_start DATETIME(6) NOT NULL,
    window_end DATETIME(6) NOT NULL,
    observed_at DATETIME(6) NOT NULL,
    actor_subject VARCHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (problem_id),
    KEY idx_ai_ops_wf_problem_tenant_workflow_window (tenant_id, workflow_id, window_start, window_end),
    CONSTRAINT ck_ai_ops_wf_problem_source_type CHECK (source_type IN ('USER_BEHAVIOR', 'SYSTEM_RUN', 'SYSTEM_LOG', 'BUSINESS_KPI', 'DQC', 'APPROVAL', 'WORK_ORDER', 'EXTERNAL_WEB')),
    CONSTRAINT ck_ai_ops_wf_problem_severity CHECK (severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_ai_ops_wf_problem_dqc CHECK (dqc_status IN ('PASS', 'WARN', 'FAIL', 'UNKNOWN', 'NOT_APPLICABLE')),
    CONSTRAINT ck_ai_ops_wf_problem_status CHECK (record_status IN ('OPEN', 'ACKNOWLEDGED', 'MITIGATED', 'DISMISSED')),
    CONSTRAINT ck_ai_ops_wf_problem_window CHECK (window_end >= window_start),
    CONSTRAINT ck_ai_ops_wf_problem_fresh CHECK (fresh_until IS NULL OR fresh_until >= window_end)
);

CREATE TABLE cloudmold_ai_ops_workflow_user_feedback (
    feedback_id VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    lineage_id VARCHAR(128) NOT NULL,
    workflow_id VARCHAR(191) NOT NULL,
    workflow_version VARCHAR(64) NOT NULL,
    proposal_id VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    feedback_type VARCHAR(32) NOT NULL,
    feedback_label VARCHAR(191) NOT NULL,
    feedback_text TEXT NOT NULL,
    evidence_ref VARCHAR(255) NULL,
    summary_source_refs_json JSON NULL,
    model_summary TEXT NULL,
    metrics_json JSON NULL,
    severity VARCHAR(16) NOT NULL,
    dqc_status VARCHAR(32) NOT NULL,
    record_status VARCHAR(32) NOT NULL,
    release_eligible TINYINT(1) NOT NULL DEFAULT 0,
    corroborating_source_types_json JSON NULL,
    fresh_until DATETIME(6) NULL,
    window_start DATETIME(6) NOT NULL,
    window_end DATETIME(6) NOT NULL,
    observed_at DATETIME(6) NOT NULL,
    actor_subject VARCHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (feedback_id),
    KEY idx_ai_ops_wf_feedback_tenant_workflow_window (tenant_id, workflow_id, window_start, window_end),
    CONSTRAINT ck_ai_ops_wf_feedback_source_type CHECK (source_type IN ('USER_BEHAVIOR', 'SYSTEM_RUN', 'SYSTEM_LOG', 'BUSINESS_KPI', 'DQC', 'APPROVAL', 'WORK_ORDER', 'EXTERNAL_WEB')),
    CONSTRAINT ck_ai_ops_wf_feedback_type CHECK (feedback_type IN ('USER_FEEDBACK', 'APPROVAL_NOTE', 'RELEASE_SIGNAL', 'BUSINESS_REVIEW')),
    CONSTRAINT ck_ai_ops_wf_feedback_severity CHECK (severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_ai_ops_wf_feedback_dqc CHECK (dqc_status IN ('PASS', 'WARN', 'FAIL', 'UNKNOWN', 'NOT_APPLICABLE')),
    CONSTRAINT ck_ai_ops_wf_feedback_status CHECK (record_status IN ('RECEIVED', 'ACKNOWLEDGED', 'APPLIED', 'REJECTED')),
    CONSTRAINT ck_ai_ops_wf_feedback_window CHECK (window_end >= window_start),
    CONSTRAINT ck_ai_ops_wf_feedback_fresh CHECK (fresh_until IS NULL OR fresh_until >= window_end)
);

CREATE TABLE cloudmold_ai_ops_external_evidence_snapshot (
    snapshot_id VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    lineage_id VARCHAR(128) NOT NULL,
    workflow_id VARCHAR(191) NOT NULL,
    workflow_version VARCHAR(64) NOT NULL,
    proposal_id VARCHAR(64) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_class VARCHAR(32) NOT NULL,
    url VARCHAR(512) NOT NULL,
    published_at DATETIME(6) NULL,
    fetched_at DATETIME(6) NOT NULL,
    summary_text TEXT NOT NULL,
    content_hash_sha256 CHAR(64) NOT NULL,
    confidence DECIMAL(5, 4) NOT NULL,
    region VARCHAR(128) NULL,
    applicability VARCHAR(191) NULL,
    severity VARCHAR(16) NOT NULL,
    dqc_status VARCHAR(32) NOT NULL,
    record_status VARCHAR(32) NOT NULL,
    fresh_until DATETIME(6) NULL,
    window_start DATETIME(6) NOT NULL,
    window_end DATETIME(6) NOT NULL,
    release_eligible TINYINT(1) NOT NULL DEFAULT 0,
    actor_subject VARCHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (snapshot_id),
    UNIQUE KEY uk_ai_ops_external_snapshot_hash (tenant_id, workflow_id, content_hash_sha256, fetched_at),
    KEY idx_ai_ops_external_snapshot_tenant_workflow_window (tenant_id, workflow_id, window_start, window_end),
    CONSTRAINT ck_ai_ops_external_source_type CHECK (source_type IN ('EXTERNAL_WEB')),
    CONSTRAINT ck_ai_ops_external_source_class CHECK (source_class IN ('NEWS', 'REGULATION', 'MARKETPLACE', 'SOCIAL', 'VENDOR_DOC', 'THIRD_PARTY_ANALYSIS')),
    CONSTRAINT ck_ai_ops_external_confidence CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT ck_ai_ops_external_severity CHECK (severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_ai_ops_external_dqc CHECK (dqc_status IN ('PASS', 'WARN', 'FAIL', 'UNKNOWN', 'NOT_APPLICABLE')),
    CONSTRAINT ck_ai_ops_external_status CHECK (record_status IN ('CAPTURED', 'VERIFIED', 'STALE', 'REJECTED')),
    CONSTRAINT ck_ai_ops_external_window CHECK (window_end >= window_start),
    CONSTRAINT ck_ai_ops_external_fresh CHECK (fresh_until IS NULL OR fresh_until >= window_end),
    CONSTRAINT ck_ai_ops_external_redline CHECK (release_eligible = 0)
);
