package cn.iocoder.yudao.module.cloudmold.merchant.api;

import lombok.Data;
import lombok.experimental.Accessors;

import java.util.List;

@Data
@Accessors(chain = true)
public class MerchantCommandResult {
    private Long operationId;
    private String applicationId;
    private String onboardingStatus;
    private Long applicationVersion;
    private String legalEntityId;
    private String legalEntityStatus;
    private Long legalEntityVersion;
    private String merchantId;
    private String merchantStatus;
    private Long merchantVersion;
    private String shopId;
    private String shopStatus;
    private Long shopVersion;
    private String ownerAssignmentId;
    private String ownerAssignmentStatus;
    private String sourceMappingId;
    private String sourceSystem;
    private String sourceType;
    private String sourceId;
    private String targetType;
    private String targetId;
    private java.time.Instant validFrom;
    private java.time.Instant validTo;
    private String verificationRef;
    private String migrationRunId;
    private String sourceMappingStatus;
    private Long sourceMappingVersion;
    private String listingUnpublishSagaId;
    private Integer affectedListingCount;
    private String admissionId;
    private String admissionStatus;
    private Long admissionVersion;
    private String evidencePackageId;
    private String evidencePackageStatus;
    private Long evidencePackageVersion;
    private String evidencePackageRef;
    private List<MerchantManagedEvidenceItem> evidenceItems;
    private String diagnosticId;
    private String diagnosticStatus;
    private Long diagnosticVersion;
    private String recommendationCode;
    private String recommendationSummary;
    private String inspectionTaskId;
    private String inspectionTaskStatus;
    private Long inspectionTaskVersion;
    private String inspectionOutcomeEvidenceRef;
    private String invitationId;
    private String invitationCode;
    private String invitationStatus;
    private Long invitationVersion;
    private String buyerAssignmentId;
    private String buyerAssignmentStatus;
    private Long buyerAssignmentVersion;
    private String buyerTlPrincipalId;
    private String buyerPrincipalId;
    private String gradeDecisionId;
    private String gradeCode;
    private String gradeTransitionDecision;
    private String gradeDecisionStatus;
    private Long gradeDecisionVersion;
    private List<MerchantBenefitEntitlementItem> benefitEntitlements;
    private String probationAssessmentId;
    private String probationAssessmentStatus;
    private Long probationAssessmentVersion;
    private List<MerchantProbationGateItem> probationGates;
    private String scorecardId;
    private String scorecardMonth;
    private String scorecardStatus;
    private Long scorecardVersion;
    private List<MerchantScorecardItem> scorecardItems;
    private String exitDecisionId;
    private String exitReasonType;
    private String exitDecisionStatus;
    private Long exitDecisionVersion;
    private String finalReviewId;
    private String finalReviewStatus;
    private Long finalReviewVersion;
    private String reviewDecision;
    private boolean duplicate;
}
