CREATE TABLE IF NOT EXISTS cloudmold_procurement_operation (
    operation_id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    attempt_token CHAR(36) NOT NULL,
    status INT NOT NULL,
    aggregate_type VARCHAR(64) NULL,
    aggregate_id VARCHAR(128) NULL,
    result_json JSON NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (operation_id),
    UNIQUE KEY uk_procurement_operation (tenant_id, idempotency_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Idempotent procurement command envelope';

CREATE TABLE IF NOT EXISTS cloudmold_procurement_order (
    order_id VARCHAR(128) NOT NULL,
    tenant_id BIGINT NOT NULL,
    order_code VARCHAR(64) NOT NULL,
    source_business_type VARCHAR(64) NOT NULL,
    source_business_ref VARCHAR(128) NOT NULL,
    supplier_ref VARCHAR(128) NOT NULL,
    canonical_sku_id VARCHAR(128) NOT NULL,
    canonical_warehouse_id VARCHAR(128) NOT NULL,
    ordered_quantity DECIMAL(24, 6) NOT NULL,
    uom_code VARCHAR(16) NOT NULL,
    unit_cost_minor BIGINT NOT NULL,
    total_amount_minor BIGINT NOT NULL,
    currency_code CHAR(3) NOT NULL,
    lead_time_days INT NOT NULL,
    required_delivery_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_by_principal_id VARCHAR(128) NOT NULL,
    dispatched_by_principal_id VARCHAR(128) NULL,
    supplier_confirmed_by_principal_id VARCHAR(128) NULL,
    cancelled_by_principal_id VARCHAR(128) NULL,
    closed_by_principal_id VARCHAR(128) NULL,
    reason_code VARCHAR(64) NULL,
    remark VARCHAR(255) NULL,
    projection_source_system VARCHAR(32) NULL,
    projection_document_type VARCHAR(32) NULL,
    projection_external_document_id VARCHAR(128) NULL,
    projection_external_document_no VARCHAR(128) NULL,
    projection_document_status VARCHAR(32) NULL,
    projection_evidence_sha256 CHAR(64) NULL,
    version BIGINT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    dispatched_at DATETIME(6) NULL,
    supplier_confirmed_at DATETIME(6) NULL,
    cancelled_at DATETIME(6) NULL,
    closed_at DATETIME(6) NULL,
    PRIMARY KEY (order_id),
    UNIQUE KEY uk_procurement_order_tenant_id (tenant_id, order_id),
    UNIQUE KEY uk_procurement_order_code (tenant_id, order_code),
    UNIQUE KEY uk_procurement_source_ref (tenant_id, source_business_type, source_business_ref),
    UNIQUE KEY uk_procurement_projection_ref (tenant_id, projection_source_system, projection_document_type, projection_external_document_id),
    KEY idx_procurement_status (tenant_id, status, updated_at),
    CONSTRAINT ck_procurement_order_quantity CHECK (ordered_quantity > 0),
    CONSTRAINT ck_procurement_unit_cost CHECK (unit_cost_minor >= 0),
    CONSTRAINT ck_procurement_total_amount CHECK (total_amount_minor >= 0),
    CONSTRAINT ck_procurement_currency CHECK (currency_code REGEXP '^[A-Z]{3}$'),
    CONSTRAINT ck_procurement_status CHECK (status IN (
        'CREATED','DISPATCHED','SUPPLIER_CONFIRMED','CANCELLED','CLOSED')),
    CONSTRAINT ck_procurement_uom CHECK (uom_code REGEXP '^[A-Z][A-Z0-9_]{0,15}$'),
    CONSTRAINT ck_procurement_projection_status CHECK (
        projection_document_status IS NULL OR projection_document_status='PREPARE')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Canonical procurement purchase-order authority with optional ERP/WMS prepare projection';
