package cn.iocoder.yudao.module.cloudmold.finance.api;

public enum FinanceCloseOperation {
    OPEN_ACCOUNTING_PERIOD,
    IMPORT_CHANNEL_STATEMENT,
    RECONCILE_CHANNEL_STATEMENT,
    RESOLVE_RECONCILIATION_DIFFERENCE,
    CREATE_SETTLEMENT_BATCH,
    CONFIRM_SETTLEMENT,
    PREPARE_JOURNAL_ENTRY,
    POST_JOURNAL_ENTRY,
    CLOSE_ACCOUNTING_PERIOD
}
