-- Durable execution ledger for CloudMold Skill orchestration.

CREATE TABLE IF NOT EXISTS cloudmold_skill_task_instance (
  tenant_id BIGINT NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  run_id VARCHAR(64) NOT NULL,
  skill_id VARCHAR(191) NOT NULL,
  skill_version VARCHAR(64) NOT NULL,
  client_request_key VARCHAR(191) NOT NULL,
  input_json MEDIUMTEXT NOT NULL,
  input_sha256 CHAR(64) NOT NULL,
  risk_level VARCHAR(2) NOT NULL,
  approval_ref VARCHAR(191) NULL,
  submitter_id BIGINT NOT NULL,
  submitter_type INT NOT NULL,
  operator_id BIGINT NOT NULL,
  operator_type INT NOT NULL,
  status VARCHAR(32) NOT NULL,
  current_step_code VARCHAR(128) NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL,
  next_retry_at DATETIME(6) NULL,
  lease_owner VARCHAR(191) NULL,
  lease_until DATETIME(6) NULL,
  last_error_code VARCHAR(128) NULL,
  last_error_message VARCHAR(2000) NULL,
  version BIGINT NOT NULL DEFAULT 0,
  started_at DATETIME(6) NULL,
  completed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (tenant_id, task_id),
  UNIQUE KEY uk_skill_task_request (tenant_id, skill_id, client_request_key),
  KEY idx_skill_task_due (status, next_retry_at, lease_until),
  KEY idx_skill_task_run (tenant_id, run_id),
  CONSTRAINT chk_skill_task_risk CHECK (risk_level IN ('R1','R2','R3')),
  CONSTRAINT chk_skill_task_status CHECK (status IN ('QUEUED','RUNNING','SUCCEEDED','NEEDS_REVIEW')),
  CONSTRAINT chk_skill_task_attempts CHECK (attempt_count >= 0 AND max_attempts > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cloudmold_skill_task_step (
  tenant_id BIGINT NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  step_code VARCHAR(128) NOT NULL,
  step_order INT NOT NULL,
  capability_id VARCHAR(255) NOT NULL,
  operation_type VARCHAR(8) NOT NULL,
  argument_template_json MEDIUMTEXT NOT NULL,
  request_json MEDIUMTEXT NULL,
  request_sha256 CHAR(64) NULL,
  result_json MEDIUMTEXT NULL,
  result_sha256 CHAR(64) NULL,
  idempotency_key VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  last_error_code VARCHAR(128) NULL,
  last_error_message VARCHAR(2000) NULL,
  started_at DATETIME(6) NULL,
  completed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (tenant_id, task_id, step_code),
  UNIQUE KEY uk_skill_task_step_order (tenant_id, task_id, step_order),
  UNIQUE KEY uk_skill_task_step_idempotency (tenant_id, idempotency_key),
  CONSTRAINT fk_skill_task_step_instance FOREIGN KEY (tenant_id, task_id)
    REFERENCES cloudmold_skill_task_instance (tenant_id, task_id),
  CONSTRAINT chk_skill_task_step_operation CHECK (operation_type IN ('READ','WRITE')),
  CONSTRAINT chk_skill_task_step_status CHECK (status IN ('PENDING','RUNNING','SUCCEEDED','FAILED_RETRYABLE','NEEDS_REVIEW')),
  CONSTRAINT chk_skill_task_step_order CHECK (step_order > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cloudmold_skill_task_history (
  history_id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  aggregate_version BIGINT NOT NULL,
  previous_status VARCHAR(32) NULL,
  current_status VARCHAR(32) NOT NULL,
  current_step_code VARCHAR(128) NULL,
  detail_code VARCHAR(128) NOT NULL,
  detail_message VARCHAR(2000) NULL,
  actor_id BIGINT NOT NULL,
  actor_type INT NOT NULL,
  occurred_at DATETIME(6) NOT NULL,
  PRIMARY KEY (history_id),
  UNIQUE KEY uk_skill_task_history_version (tenant_id, task_id, aggregate_version),
  KEY idx_skill_task_history_time (tenant_id, task_id, occurred_at),
  CONSTRAINT fk_skill_task_history_instance FOREIGN KEY (tenant_id, task_id)
    REFERENCES cloudmold_skill_task_instance (tenant_id, task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
