CREATE TABLE cloudmold_promotion_operation (
    operation_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    operation_type VARCHAR(64) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    attempt_token CHAR(36) NOT NULL,
    status SMALLINT NOT NULL,
    aggregate_type VARCHAR(64) NULL,
    aggregate_id VARCHAR(64) NULL,
    result_json JSON NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (operation_id),
    UNIQUE KEY uk_promotion_operation_tenant_key (tenant_id, idempotency_key)
) ENGINE=InnoDB;

CREATE TABLE cloudmold_promotion_campaign (
    campaign_id VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    campaign_code VARCHAR(64) NOT NULL,
    campaign_kind VARCHAR(32) NOT NULL,
    name VARCHAR(128) NOT NULL,
    status VARCHAR(24) NOT NULL,
    starts_at DATETIME(6) NOT NULL,
    ends_at DATETIME(6) NOT NULL,
    version BIGINT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (campaign_id),
    UNIQUE KEY uk_promotion_campaign_tenant_code (tenant_id, campaign_code),
    KEY idx_promotion_campaign_tenant_status (tenant_id, status, starts_at, ends_at)
) ENGINE=InnoDB;

CREATE TABLE cloudmold_promotion_coupon_template (
    template_id VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    template_code VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(64) NULL,
    title VARCHAR(128) NOT NULL,
    benefit_type VARCHAR(24) NOT NULL,
    face_amount_minor BIGINT NULL,
    threshold_minor BIGINT NOT NULL,
    discount_basis_points INT NULL,
    cap_amount_minor BIGINT NULL,
    currency_code CHAR(3) NOT NULL,
    funder_type VARCHAR(24) NOT NULL,
    merchant_id VARCHAR(64) NULL,
    status VARCHAR(24) NOT NULL,
    valid_from DATETIME(6) NOT NULL,
    valid_to DATETIME(6) NOT NULL,
    version BIGINT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (template_id),
    UNIQUE KEY uk_promotion_template_tenant_code (tenant_id, template_code),
    KEY idx_promotion_template_campaign (tenant_id, campaign_id, status),
    CONSTRAINT ck_promotion_template_amounts CHECK (threshold_minor >= 0 AND (face_amount_minor IS NULL OR face_amount_minor > 0))
) ENGINE=InnoDB;

CREATE TABLE cloudmold_promotion_coupon_entitlement (
    entitlement_id VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    entitlement_code VARCHAR(64) NOT NULL,
    template_id VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(64) NULL,
    principal_id VARCHAR(64) NOT NULL,
    order_ref VARCHAR(128) NULL,
    face_amount_minor BIGINT NULL,
    threshold_minor BIGINT NOT NULL,
    currency_code CHAR(3) NOT NULL,
    status VARCHAR(24) NOT NULL,
    version BIGINT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (entitlement_id),
    UNIQUE KEY uk_promotion_entitlement_tenant_code (tenant_id, entitlement_code),
    KEY idx_promotion_entitlement_principal (tenant_id, principal_id, status),
    KEY idx_promotion_entitlement_template (tenant_id, template_id)
) ENGINE=InnoDB;

CREATE TABLE cloudmold_promotion_coupon_entitlement_ledger (
    ledger_entry_id VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    entitlement_id VARCHAR(64) NOT NULL,
    entitlement_version BIGINT NOT NULL,
    operation_id BIGINT UNSIGNED NOT NULL,
    operation_type VARCHAR(64) NOT NULL,
    previous_status VARCHAR(24) NULL,
    current_status VARCHAR(24) NOT NULL,
    order_ref VARCHAR(128) NULL,
    reason VARCHAR(256) NULL,
    face_amount_minor BIGINT NULL,
    threshold_minor BIGINT NOT NULL,
    currency_code CHAR(3) NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (ledger_entry_id),
    UNIQUE KEY uk_promotion_entitlement_ledger_version (tenant_id, entitlement_id, entitlement_version),
    UNIQUE KEY uk_promotion_entitlement_ledger_operation (tenant_id, operation_id),
    KEY idx_promotion_entitlement_ledger_time (tenant_id, occurred_at)
) ENGINE=InnoDB;

CREATE TABLE cloudmold_promotion_advertising_placement (
    placement_id VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    placement_code VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    channel_code VARCHAR(32) NOT NULL,
    page_code VARCHAR(64) NOT NULL,
    slot_code VARCHAR(64) NOT NULL,
    creative_ref VARCHAR(128) NOT NULL,
    status VARCHAR(24) NOT NULL,
    valid_from DATETIME(6) NOT NULL,
    valid_to DATETIME(6) NOT NULL,
    version BIGINT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (placement_id),
    UNIQUE KEY uk_promotion_placement_tenant_code (tenant_id, placement_code),
    KEY idx_promotion_placement_campaign (tenant_id, campaign_id, status)
) ENGINE=InnoDB;

CREATE TABLE cloudmold_promotion_advertising_interaction (
    interaction_id VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    deduplication_key VARCHAR(128) NOT NULL,
    interaction_type VARCHAR(24) NOT NULL,
    placement_id VARCHAR(64) NOT NULL,
    campaign_id VARCHAR(64) NOT NULL,
    principal_id VARCHAR(64) NULL,
    session_id VARCHAR(128) NULL,
    source_interaction_id VARCHAR(64) NULL,
    order_ref VARCHAR(128) NULL,
    attribution_amount_minor BIGINT NULL,
    currency_code CHAR(3) NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (interaction_id),
    UNIQUE KEY uk_promotion_interaction_tenant_dedup (tenant_id, deduplication_key),
    KEY idx_promotion_interaction_placement_time (tenant_id, placement_id, occurred_at),
    KEY idx_promotion_interaction_source (tenant_id, source_interaction_id),
    CONSTRAINT ck_promotion_attribution_amount CHECK (attribution_amount_minor IS NULL OR attribution_amount_minor >= 0)
) ENGINE=InnoDB;
