-- Minimal additive MES schema required by the governed HSF work-order slice.
-- This intentionally contains no demo/master data: the Skill creates every
-- business prerequisite through typed, idempotent Dubbo capabilities.

CREATE TABLE IF NOT EXISTS `mes_md_unit_measure` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) NOT NULL,
  `name` varchar(255) NOT NULL,
  `primary_flag` bit(1) NOT NULL DEFAULT b'1',
  `primary_id` bigint DEFAULT NULL,
  `change_rate` decimal(12,4) DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT '',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 计量单位表';

CREATE TABLE IF NOT EXISTS `mes_md_item_type` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) NOT NULL,
  `name` varchar(255) NOT NULL,
  `parent_id` bigint NOT NULL DEFAULT 0,
  `item_or_product` varchar(20) NOT NULL,
  `sort` int NOT NULL DEFAULT 0,
  `status` tinyint NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT '',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 物料产品分类表';

CREATE TABLE IF NOT EXISTS `mes_md_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) NOT NULL,
  `name` varchar(255) NOT NULL,
  `specification` varchar(500) DEFAULT NULL,
  `unit_measure_id` bigint NOT NULL DEFAULT 0,
  `item_type_id` bigint NOT NULL DEFAULT 0,
  `status` tinyint NOT NULL DEFAULT 0,
  `safe_stock_flag` bit(1) NOT NULL DEFAULT b'0',
  `min_stock` decimal(12,4) NOT NULL DEFAULT 0,
  `max_stock` decimal(12,4) NOT NULL DEFAULT 0,
  `high_value` bit(1) NOT NULL DEFAULT b'0',
  `batch_flag` bit(1) NOT NULL DEFAULT b'1',
  `remark` varchar(500) DEFAULT '',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 物料产品表';

CREATE TABLE IF NOT EXISTS `mes_md_item_batch_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `item_id` bigint NOT NULL,
  `produce_date_flag` bit(1) NOT NULL DEFAULT b'0',
  `expire_date_flag` bit(1) NOT NULL DEFAULT b'0',
  `receipt_date_flag` bit(1) NOT NULL DEFAULT b'0',
  `vendor_flag` bit(1) NOT NULL DEFAULT b'0',
  `client_flag` bit(1) NOT NULL DEFAULT b'0',
  `sales_order_code_flag` bit(1) NOT NULL DEFAULT b'0',
  `purchase_order_code_flag` bit(1) NOT NULL DEFAULT b'0',
  `work_order_flag` bit(1) NOT NULL DEFAULT b'0',
  `task_flag` bit(1) NOT NULL DEFAULT b'0',
  `workstation_flag` bit(1) NOT NULL DEFAULT b'0',
  `tool_flag` bit(1) NOT NULL DEFAULT b'0',
  `mold_flag` bit(1) NOT NULL DEFAULT b'0',
  `lot_number_flag` bit(1) NOT NULL DEFAULT b'0',
  `quality_status_flag` bit(1) NOT NULL DEFAULT b'0',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_item_id` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 物料批次属性配置表';

CREATE TABLE IF NOT EXISTS `mes_md_product_bom` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `item_id` bigint NOT NULL,
  `bom_item_id` bigint NOT NULL,
  `quantity` decimal(12,4) NOT NULL DEFAULT 0,
  `status` tinyint NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 产品 BOM 表';

CREATE TABLE IF NOT EXISTS `mes_pro_work_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) NOT NULL,
  `name` varchar(255) NOT NULL,
  `type` tinyint NOT NULL DEFAULT 1,
  `order_source_type` tinyint NOT NULL,
  `order_source_code` varchar(64) DEFAULT NULL,
  `product_id` bigint NOT NULL,
  `quantity` decimal(14,2) NOT NULL DEFAULT 0,
  `quantity_produced` decimal(14,2) NOT NULL DEFAULT 0,
  `quantity_changed` decimal(14,2) NOT NULL DEFAULT 0,
  `quantity_scheduled` decimal(14,2) NOT NULL DEFAULT 0,
  `client_id` bigint DEFAULT NULL,
  `vendor_id` bigint DEFAULT NULL,
  `batch_code` varchar(64) DEFAULT NULL,
  `request_date` datetime NOT NULL,
  `parent_id` bigint NOT NULL DEFAULT 0,
  `finish_date` datetime DEFAULT NULL,
  `cancel_date` datetime DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT '',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 生产工单';

CREATE TABLE IF NOT EXISTS `mes_pro_work_order_bom` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `work_order_id` bigint NOT NULL,
  `item_id` bigint NOT NULL,
  `quantity` decimal(14,2) NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT '',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 生产工单 BOM';

CREATE TABLE IF NOT EXISTS `mes_pro_task` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) NOT NULL,
  `name` varchar(255) NOT NULL,
  `work_order_id` bigint NOT NULL,
  `workstation_id` bigint NOT NULL,
  `route_id` bigint NOT NULL,
  `process_id` bigint NOT NULL,
  `item_id` bigint NOT NULL,
  `quantity` decimal(14,2) NOT NULL DEFAULT 0,
  `produced_quantity` decimal(14,2) NOT NULL DEFAULT 0,
  `qualify_quantity` decimal(14,2) NOT NULL DEFAULT 0,
  `unqualify_quantity` decimal(14,2) NOT NULL DEFAULT 0,
  `changed_quantity` decimal(14,2) NOT NULL DEFAULT 0,
  `client_id` bigint DEFAULT NULL,
  `start_time` datetime DEFAULT NULL,
  `duration` int NOT NULL DEFAULT 1,
  `end_time` datetime DEFAULT NULL,
  `color_code` char(7) DEFAULT '#00AEF3',
  `finish_date` datetime DEFAULT NULL,
  `cancel_date` datetime DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT '',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 生产任务';

CREATE TABLE IF NOT EXISTS `mes_wm_barcode_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `format` tinyint NOT NULL,
  `biz_type` smallint NOT NULL,
  `content_format` varchar(255) NOT NULL,
  `content_example` varchar(255) DEFAULT NULL,
  `auto_generate_flag` bit(1) NOT NULL DEFAULT b'1',
  `default_template` varchar(255) DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT '',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_type` (`biz_type`,`deleted`,`tenant_id`),
  KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 条码配置表';

CREATE TABLE IF NOT EXISTS `mes_wm_barcode` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `config_id` bigint DEFAULT NULL,
  `format` tinyint NOT NULL,
  `biz_type` smallint NOT NULL,
  `content` varchar(255) NOT NULL,
  `biz_id` bigint NOT NULL,
  `biz_code` varchar(64) DEFAULT NULL,
  `biz_name` varchar(255) DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `remark` varchar(500) DEFAULT '',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_config_id` (`config_id`),
  KEY `idx_biz_type_id` (`biz_type`,`biz_id`),
  KEY `idx_content` (`content`(100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 条码清单表';
