CREATE TABLE IF NOT EXISTS cloudmold_supplier_operation (
    operation_id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    attempt_token CHAR(36) NOT NULL,
    status INT NOT NULL,
    aggregate_type VARCHAR(64) NULL,
    aggregate_id VARCHAR(128) NULL,
    result_json JSON NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (operation_id),
    UNIQUE KEY uk_supplier_operation (tenant_id, idempotency_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Idempotent canonical supplier sourcing command envelope';

CREATE TABLE IF NOT EXISTS cloudmold_supplier_profile (
    supplier_id VARCHAR(128) NOT NULL,
    tenant_id BIGINT NOT NULL,
    supplier_code VARCHAR(64) NOT NULL,
    supplier_name VARCHAR(191) NOT NULL,
    country_code CHAR(2) NOT NULL,
    capability_summary VARCHAR(1000) NOT NULL,
    risk_level VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    admission_status VARCHAR(32) NOT NULL,
    qualification_evidence_sha256 CHAR(64) NULL,
    risk_evidence_sha256 CHAR(64) NULL,
    created_by_principal_id VARCHAR(128) NOT NULL,
    submitted_by_principal_id VARCHAR(128) NULL,
    admitted_by_principal_id VARCHAR(128) NULL,
    reason_code VARCHAR(64) NULL,
    version BIGINT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    admission_submitted_at DATETIME(6) NULL,
    admitted_at DATETIME(6) NULL,
    PRIMARY KEY (supplier_id),
    UNIQUE KEY uk_supplier_profile_tenant_id (tenant_id, supplier_id),
    UNIQUE KEY uk_supplier_profile_code (tenant_id, supplier_code),
    KEY idx_supplier_admission (tenant_id, admission_status, updated_at),
    CONSTRAINT ck_supplier_country CHECK (country_code REGEXP '^[A-Z]{2}$'),
    CONSTRAINT ck_supplier_risk CHECK (risk_level IN ('LOW','MEDIUM','HIGH')),
    CONSTRAINT ck_supplier_status CHECK (status IN ('CANDIDATE','ACTIVE','SUSPENDED','EXITED')),
    CONSTRAINT ck_supplier_admission CHECK (admission_status IN ('DRAFT','UNDER_REVIEW','ADMITTED','REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Canonical supplier candidate and admission authority';

CREATE TABLE IF NOT EXISTS cloudmold_supplier_sourcing_case (
    sourcing_case_id VARCHAR(128) NOT NULL,
    tenant_id BIGINT NOT NULL,
    rfq_code VARCHAR(64) NOT NULL,
    request_ref VARCHAR(128) NOT NULL,
    canonical_sku_id VARCHAR(128) NOT NULL,
    target_quantity DECIMAL(24, 6) NOT NULL,
    uom_code VARCHAR(16) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    max_unit_cost_minor BIGINT NOT NULL,
    required_delivery_date DATE NOT NULL,
    requirements VARCHAR(2000) NOT NULL,
    status VARCHAR(32) NOT NULL,
    awarded_supplier_id VARCHAR(128) NULL,
    awarded_quote_id VARCHAR(128) NULL,
    decision_rationale VARCHAR(2000) NULL,
    created_by_principal_id VARCHAR(128) NOT NULL,
    awarded_by_principal_id VARCHAR(128) NULL,
    version BIGINT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    awarded_at DATETIME(6) NULL,
    PRIMARY KEY (sourcing_case_id),
    UNIQUE KEY uk_supplier_sourcing_case_tenant (tenant_id, sourcing_case_id),
    UNIQUE KEY uk_supplier_sourcing_rfq (tenant_id, rfq_code),
    UNIQUE KEY uk_supplier_sourcing_request (tenant_id, request_ref),
    KEY idx_supplier_sourcing_status (tenant_id, status, updated_at),
    CONSTRAINT ck_supplier_sourcing_quantity CHECK (target_quantity > 0),
    CONSTRAINT ck_supplier_sourcing_cost CHECK (max_unit_cost_minor >= 0),
    CONSTRAINT ck_supplier_sourcing_currency CHECK (currency_code REGEXP '^[A-Z]{3}$'),
    CONSTRAINT ck_supplier_sourcing_uom CHECK (uom_code REGEXP '^[A-Z][A-Z0-9_]{0,15}$'),
    CONSTRAINT ck_supplier_sourcing_status CHECK (status IN ('OPEN','QUOTING','EVALUATING','AWARDED','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Canonical RFQ and supplier award decision authority';

CREATE TABLE IF NOT EXISTS cloudmold_supplier_quote (
    quote_id VARCHAR(128) NOT NULL,
    tenant_id BIGINT NOT NULL,
    sourcing_case_id VARCHAR(128) NOT NULL,
    supplier_id VARCHAR(128) NOT NULL,
    quote_version INT NOT NULL,
    unit_cost_minor BIGINT NOT NULL,
    moq DECIMAL(24, 6) NOT NULL,
    lead_time_days INT NOT NULL,
    capacity_quantity DECIMAL(24, 6) NOT NULL,
    valid_until DATE NOT NULL,
    terms_summary VARCHAR(1000) NOT NULL,
    status VARCHAR(32) NOT NULL,
    submitted_by_principal_id VARCHAR(128) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (quote_id),
    UNIQUE KEY uk_supplier_quote_tenant (tenant_id, quote_id),
    UNIQUE KEY uk_supplier_quote_version (tenant_id, sourcing_case_id, supplier_id, quote_version),
    KEY idx_supplier_quote_case (tenant_id, sourcing_case_id, status),
    CONSTRAINT ck_supplier_quote_version CHECK (quote_version > 0),
    CONSTRAINT ck_supplier_quote_cost CHECK (unit_cost_minor >= 0),
    CONSTRAINT ck_supplier_quote_moq CHECK (moq > 0),
    CONSTRAINT ck_supplier_quote_lead_time CHECK (lead_time_days >= 0),
    CONSTRAINT ck_supplier_quote_capacity CHECK (capacity_quantity > 0),
    CONSTRAINT ck_supplier_quote_status CHECK (status IN ('SUBMITTED','AWARDED','REJECTED','WITHDRAWN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Versioned supplier RFQ quotation authority';

CREATE TABLE IF NOT EXISTS cloudmold_supplier_sample_evaluation (
    evaluation_id VARCHAR(128) NOT NULL,
    tenant_id BIGINT NOT NULL,
    sourcing_case_id VARCHAR(128) NOT NULL,
    supplier_id VARCHAR(128) NOT NULL,
    quote_id VARCHAR(128) NOT NULL,
    quality_score INT NOT NULL,
    fit_score INT NOT NULL,
    delivery_score INT NOT NULL,
    risk_score INT NOT NULL,
    result VARCHAR(16) NOT NULL,
    notes VARCHAR(1000) NOT NULL,
    evaluated_by_principal_id VARCHAR(128) NOT NULL,
    evaluated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (evaluation_id),
    UNIQUE KEY uk_supplier_sample_tenant (tenant_id, evaluation_id),
    UNIQUE KEY uk_supplier_sample_quote (tenant_id, sourcing_case_id, quote_id),
    KEY idx_supplier_sample_result (tenant_id, sourcing_case_id, result),
    CONSTRAINT ck_supplier_sample_quality CHECK (quality_score BETWEEN 0 AND 100),
    CONSTRAINT ck_supplier_sample_fit CHECK (fit_score BETWEEN 0 AND 100),
    CONSTRAINT ck_supplier_sample_delivery CHECK (delivery_score BETWEEN 0 AND 100),
    CONSTRAINT ck_supplier_sample_risk CHECK (risk_score BETWEEN 0 AND 100),
    CONSTRAINT ck_supplier_sample_result CHECK (result IN ('PASS','FAIL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Canonical sample evaluation evidence for supplier sourcing';
