CREATE TABLE IF NOT EXISTS cloudmold_app_recommendation_decision (
    decision_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    session_id CHAR(36) NOT NULL,
    scene_code VARCHAR(32) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    decision_token VARCHAR(128) NOT NULL,
    result_set_token VARCHAR(128) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    ttl_seconds INT NOT NULL,
    item_count INT NOT NULL,
    generated_at DATETIME(6) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (decision_id),
    UNIQUE KEY uk_app_recommendation_decision_token (tenant_id, decision_token),
    UNIQUE KEY uk_app_recommendation_result_set_token (tenant_id, result_set_token),
    KEY idx_app_recommendation_session_scene_expiry (tenant_id, session_id, scene_code, expires_at),
    KEY idx_app_recommendation_request_hash (tenant_id, session_id, scene_code, request_hash, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cloudmold_app_recommendation_item (
    item_id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    decision_id CHAR(36) NOT NULL,
    rank_no INT NOT NULL,
    reason_code VARCHAR(64) NOT NULL,
    listing_id CHAR(36) NOT NULL,
    listing_no VARCHAR(64) NOT NULL,
    listing_title VARCHAR(256) NOT NULL,
    primary_image_url VARCHAR(512) NULL,
    listing_offer_id CHAR(36) NOT NULL,
    merchant_id CHAR(36) NOT NULL,
    shop_id CHAR(36) NOT NULL,
    channel_code VARCHAR(32) NOT NULL,
    canonical_spu_id CHAR(36) NOT NULL,
    canonical_sku_id CHAR(36) NOT NULL,
    price_minor BIGINT NOT NULL,
    currency_code VARCHAR(8) NOT NULL,
    inventory_version BIGINT NULL,
    available_quantity DECIMAL(24,6) NULL,
    quality_status VARCHAR(32) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (item_id),
    UNIQUE KEY uk_app_recommendation_item_rank (tenant_id, decision_id, rank_no),
    UNIQUE KEY uk_app_recommendation_item_listing (tenant_id, decision_id, listing_id),
    KEY idx_app_recommendation_item_offer (tenant_id, listing_offer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
