CREATE TABLE IF NOT EXISTS `cloudmold_crossborder_operation` (
  `operation_id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `idempotency_key` varchar(128) NOT NULL,
  `command_type` varchar(64) NOT NULL,
  `request_hash` char(64) NOT NULL,
  `attempt_token` varchar(64) NOT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `aggregate_type` varchar(64) DEFAULT NULL,
  `aggregate_id` varchar(128) DEFAULT NULL,
  `result_json` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`operation_id`),
  UNIQUE KEY `uk_cm_xb_operation_tenant_idem` (`tenant_id`,`idempotency_key`),
  KEY `idx_cm_xb_operation_aggregate` (`tenant_id`,`aggregate_id`),
  CONSTRAINT `ck_cm_xb_operation_status` CHECK (`status` IN (0,10)),
  CONSTRAINT `ck_cm_xb_operation_hash` CHECK (`request_hash` REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `cloudmold_crossborder_case` (
  `case_id` varchar(128) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `case_no` varchar(32) NOT NULL,
  `order_id` varchar(128) NOT NULL,
  `fulfillment_id` varchar(128) NOT NULL,
  `trade_mode` varchar(32) NOT NULL,
  `origin_country` char(2) NOT NULL,
  `destination_country` char(2) NOT NULL,
  `status` varchar(48) NOT NULL,
  `assessment_id` varchar(128) DEFAULT NULL,
  `route_code` varchar(64) DEFAULT NULL,
  `route_carrier_code` varchar(64) DEFAULT NULL,
  `route_service_level` varchar(64) DEFAULT NULL,
  `route_sla_days` int DEFAULT NULL,
  `approval_ref` varchar(128) DEFAULT NULL,
  `declaration_id` varchar(128) DEFAULT NULL,
  `hs_code` varchar(12) DEFAULT NULL,
  `goods_description` varchar(255) DEFAULT NULL,
  `quantity` decimal(18,6) DEFAULT NULL,
  `declared_amount_minor` bigint DEFAULT NULL,
  `currency` char(3) DEFAULT NULL,
  `declaration_evidence_ref` varchar(255) DEFAULT NULL,
  `document_order_ref` varchar(128) DEFAULT NULL,
  `document_payment_ref` varchar(128) DEFAULT NULL,
  `document_logistics_ref` varchar(128) DEFAULT NULL,
  `document_validation_evidence_ref` varchar(255) DEFAULT NULL,
  `booking_ref` varchar(128) DEFAULT NULL,
  `booking_carrier_code` varchar(64) DEFAULT NULL,
  `booking_service_level` varchar(64) DEFAULT NULL,
  `label_ref` varchar(128) DEFAULT NULL,
  `tracking_number` varchar(128) DEFAULT NULL,
  `handover_ref` varchar(128) DEFAULT NULL,
  `customs_declaration_ref` varchar(128) DEFAULT NULL,
  `customs_release_ref` varchar(128) DEFAULT NULL,
  `delivery_evidence_ref` varchar(255) DEFAULT NULL,
  `close_reason` varchar(255) DEFAULT NULL,
  `created_by_principal_id` varchar(128) NOT NULL,
  `version` bigint NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `closed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`case_id`),
  UNIQUE KEY `uk_cm_xb_case_tenant_case` (`tenant_id`,`case_id`),
  UNIQUE KEY `uk_cm_xb_case_tenant_no` (`tenant_id`,`case_no`),
  KEY `idx_cm_xb_case_order` (`tenant_id`,`order_id`),
  KEY `idx_cm_xb_case_fulfillment` (`tenant_id`,`fulfillment_id`),
  CONSTRAINT `ck_cm_xb_case_trade_mode` CHECK (`trade_mode` = 'DIRECT_MAIL'),
  CONSTRAINT `ck_cm_xb_case_countries` CHECK (`origin_country` = 'CN' AND `destination_country` = 'US'),
  CONSTRAINT `ck_cm_xb_case_status` CHECK (`status` IN (
    'DRAFT','COMPLIANCE_ASSESSED','ROUTE_SELECTED','COMPLIANCE_APPROVED','DECLARATION_ASSEMBLED',
    'DOCUMENTS_VALIDATED','CARRIER_BOOKED','LABEL_RECORDED','HANDED_OVER','CUSTOMS_SUBMITTED',
    'CUSTOMS_RELEASED','DELIVERED','CLOSED')),
  CONSTRAINT `ck_cm_xb_case_version` CHECK (`version` > 0),
  CONSTRAINT `ck_cm_xb_case_sla` CHECK (`route_sla_days` IS NULL OR (`route_sla_days` >= 1 AND `route_sla_days` <= 90)),
  CONSTRAINT `ck_cm_xb_case_quantity` CHECK (`quantity` IS NULL OR `quantity` > 0),
  CONSTRAINT `ck_cm_xb_case_declared_amount` CHECK (`declared_amount_minor` IS NULL OR `declared_amount_minor` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `cloudmold_crossborder_compliance_assessment` (
  `assessment_id` varchar(128) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `case_id` varchar(128) NOT NULL,
  `facts_json` json NOT NULL,
  `options_json` json NOT NULL,
  `recommendation` varchar(255) NOT NULL,
  `risks_json` json NOT NULL,
  `confidence` decimal(5,4) NOT NULL,
  `missing_facts_json` json NOT NULL,
  `evidence_ref` varchar(255) NOT NULL,
  `assessed_by_principal_id` varchar(128) NOT NULL,
  `assessed_at` datetime NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`assessment_id`),
  KEY `idx_cm_xb_assessment_case` (`tenant_id`,`case_id`,`assessed_at`),
  CONSTRAINT `fk_cm_xb_assessment_case`
    FOREIGN KEY (`tenant_id`,`case_id`)
    REFERENCES `cloudmold_crossborder_case` (`tenant_id`,`case_id`) ON DELETE CASCADE,
  CONSTRAINT `ck_cm_xb_assessment_confidence` CHECK (`confidence` >= 0 AND `confidence` <= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `cloudmold_crossborder_status_history` (
  `history_id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `case_id` varchar(128) NOT NULL,
  `aggregate_version` bigint NOT NULL,
  `operation` varchar(64) NOT NULL,
  `previous_status` varchar(48) DEFAULT NULL,
  `current_status` varchar(48) NOT NULL,
  `actor_principal_id` varchar(128) NOT NULL,
  `occurred_at` datetime NOT NULL,
  `detail_json` json NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`history_id`),
  UNIQUE KEY `uk_cm_xb_history_version` (`tenant_id`,`case_id`,`aggregate_version`),
  KEY `idx_cm_xb_history_case` (`tenant_id`,`case_id`,`history_id`),
  CONSTRAINT `fk_cm_xb_history_case`
    FOREIGN KEY (`tenant_id`,`case_id`)
    REFERENCES `cloudmold_crossborder_case` (`tenant_id`,`case_id`) ON DELETE CASCADE,
  CONSTRAINT `ck_cm_xb_history_version` CHECK (`aggregate_version` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
