package cn.iocoder.yudao.module.cloudmold.aioperations.api;

public enum AiOperationsOperation {
    REGISTER_APPLICATION,
    ACTIVATE_APPLICATION,
    SUSPEND_APPLICATION,
    RETIRE_APPLICATION,
    PUBLISH_WORKFLOW_VERSION,
    START_WORKFLOW_RUN,
    COMPLETE_WORKFLOW_RUN,
    FAIL_WORKFLOW_RUN,
    CANCEL_WORKFLOW_RUN,
    RECORD_MODEL_INVOCATION,
    RECORD_OUTCOME_FEEDBACK
}
