package cn.iocoder.yudao.module.cloudmold.promotion.api;

public enum PromotionOperation {
    CREATE_CAMPAIGN, UPDATE_CAMPAIGN, ACTIVATE_CAMPAIGN, PAUSE_CAMPAIGN, COMPLETE_CAMPAIGN, CANCEL_CAMPAIGN,
    CREATE_COUPON_TEMPLATE, ACTIVATE_COUPON_TEMPLATE, SUSPEND_COUPON_TEMPLATE, RETIRE_COUPON_TEMPLATE,
    ISSUE_COUPON_ENTITLEMENT, COLLECT_COUPON_ENTITLEMENT, RESERVE_COUPON_ENTITLEMENT,
    REDEEM_COUPON_ENTITLEMENT, RETURN_COUPON_ENTITLEMENT, EXPIRE_COUPON_ENTITLEMENT,
    VOID_COUPON_ENTITLEMENT,
    CREATE_ADVERTISING_PLACEMENT, ACTIVATE_ADVERTISING_PLACEMENT, PAUSE_ADVERTISING_PLACEMENT,
    RETIRE_ADVERTISING_PLACEMENT,
    RECORD_IMPRESSION, RECORD_CLICK, RECORD_ATTRIBUTION,
    RECORD_ADVERTISING_LEDGER_ENTRY,
    UPSERT_PROMOTION_EXPERIMENT_RESULT
}
