package cn.iocoder.yudao.module.cloudmold.procurement.controller.admin.vo;

import lombok.Data;
import lombok.experimental.Accessors;
import java.util.List;

public final class ProcurementAdminVo {
    private ProcurementAdminVo() {}
    @Data @Accessors(chain=true) public static class Page<T>{private List<T> list;private String total;}
    @Data @Accessors(chain=true) public static class CommandResult{private String aggregateId;private String aggregateType;private Long aggregateVersion;private Boolean duplicate;private String operationId;private String purchaseOrderId;private String status;}
    @Data @Accessors(chain=true) public static class RequisitionPageItem{private Long aggregateVersion;private String approvedAt;private Integer lineCount;private String requisitionCode;private String requisitionId;private String requestedByPrincipalId;private String requiredDeliveryDate;private String status;private String submittedAt;private String totalRequestedQuantity;private String uomCode;private String updatedAt;}
    @Data @Accessors(chain=true) public static class RfqPageItem{private Long aggregateVersion;private String eventCode;private String eventId;private Integer invitationCount;private Integer lineCount;private String quotationDeadline;private Integer quotationRevisionCount;private String requisitionCode;private String requisitionId;private String status;private String title;private String updatedAt;}
    @Data @Accessors(chain=true) public static class QuotationPageItem{private Long aggregateVersion;private String currencyCode;private String eventCode;private String eventId;private String grossAmountMinor;private Integer lineCount;private String quotationCode;private String quotationId;private Integer revisionNumber;private String status;private String supplierId;private String submittedAt;private String updatedAt;}
    @Data @Accessors(chain=true) public static class AwardPageItem{private Long aggregateVersion;private String awardCode;private String awardId;private String awardedQuantity;private Long eventAggregateVersion;private String eventCode;private String eventId;private Integer lineCount;private Integer purchaseOrderCount;private String status;private Integer supplierCount;private String updatedAt;}
    @Data @Accessors(chain=true) public static class AwardDetail extends AwardPageItem{private String approvedAt;private String approvedGrossAmountMinor;private String awardedNetAmountMinor;private String awardedTaxAmountMinor;private String currencyCode;private String decisionReasonCode;private List<AwardLine> lines;private String quotationDeadline;private String reviewPolicyCode;private List<StatusHistory> statusHistory;private String submittedAt;}
    @Data @Accessors(chain=true) public static class AwardLine{private String awardLineId;private String awardedGrossAmountMinor;private String awardedQuantity;private String canonicalSkuId;private Integer lineNumber;private String promisedDeliveryDate;private String quotationId;private String quotationLineId;private Integer quotationRevisionNumber;private String requisitionLineId;private String score;private String sourcingLineId;private String supplierId;private String unitNetPriceMinor;private String uomCode;private Lineage lineage;}
    @Data @Accessors(chain=true) public static class PurchaseOrderPageItem{private Long aggregateVersion;private String awardCode;private String awardId;private String currencyCode;private String grossAmountMinor;private Integer lineCount;private String orderCode;private String orderId;private String orderedQuantity;private String qualifiedQuantity;private String receivedQuantity;private Integer scheduleCount;private String status;private String supplierId;private String updatedAt;}
    @Data @Accessors(chain=true) public static class PurchaseOrderDetail extends PurchaseOrderPageItem{private String headerNetAmountMinor;private String headerTaxAmountMinor;private String issuedAt;private String legalEntityId;private List<PurchaseOrderLine> lines;private String sourceBusinessRef;private String sourceBusinessType;private List<StatusHistory> statusHistory;private String supplierAcknowledgedAt;}
    @Data @Accessors(chain=true) public static class PurchaseOrderLine{private String canonicalSkuId;private String invoicedQuantity;private String itemId;private String lineGrossAmountMinor;private String lineNetAmountMinor;private Integer lineNumber;private String lineTaxAmountMinor;private String orderedQuantity;private String qualifiedQuantity;private String receivedQuantity;private String returnedQuantity;private List<PurchaseOrderSchedule> schedules;private String taxCode;private Integer taxRateBps;private String unitNetPriceMinor;private String uomCode;private String valuationPolicyId;private String valuationPolicyVersion;private String valuationPolicyHash;private Lineage lineage;}
    @Data @Accessors(chain=true) public static class PurchaseOrderSchedule{private String canonicalWarehouseId;private String qualifiedQuantity;private String receivedQuantity;private String requiredDeliveryDate;private String scheduleId;private Integer scheduleNumber;private String scheduledQuantity;}
    @Data @Accessors(chain=true) public static class StatusHistory{private String actorPrincipalId;private String changedAt;private String fromStatus;private String reasonCode;private Long statusVersion;private String toStatus;}
    @Data @Accessors(chain=true) public static class Lineage{private String awardId;private String awardLineId;private String purchaseOrderId;private String purchaseOrderItemId;private String quotationId;private String quotationLineId;private String requisitionId;private String requisitionLineId;private String requisitionScheduleId;private String sourcingEventId;private String sourcingLineId;}
}
