package cn.iocoder.yudao.module.cloudmold.tokenplatform.api;

public enum TokenPlatformOperation {
    CREATE_MODEL_OFFERING,
    ADD_PRICING_VERSION,
    ACTIVATE_MODEL_OFFERING,
    SUSPEND_MODEL_OFFERING,
    RETIRE_MODEL_OFFERING,
    CREATE_ACCESS_CREDENTIAL,
    ACTIVATE_ACCESS_CREDENTIAL,
    REVOKE_ACCESS_CREDENTIAL,
    OPEN_QUOTA_ACCOUNT,
    POST_QUOTA_LEDGER,
    RECORD_INVOCATION_USAGE
}
