package cn.iocoder.yudao.module.cloudmold.supplyplanning.api;

public enum SupplyPlanningOperation {
    CREATE_FORECAST,
    PUBLISH_FORECAST,
    EVALUATE_FORECAST,
    CREATE_SUPPLY_PLAN,
    EVALUATE_PLAN_SCENARIO,
    RECOMMEND_PLAN_SCENARIO,
    SELECT_PLAN_SCENARIO,
    APPROVE_SUPPLY_PLAN,
    RELEASE_SUPPLY_PLAN,
    CREATE_REPLENISHMENT,
    DECIDE_REPLENISHMENT,
    CONVERT_REPLENISHMENT,
    OPEN_INVENTORY_ISSUE,
    RUN_INVENTORY_HEALTH_SCAN,
    ACKNOWLEDGE_INVENTORY_ISSUE,
    RESOLVE_INVENTORY_ISSUE
}
