CREATE TABLE IF NOT EXISTS cloudmold_commerce_behavior_operation (
    operation_id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    attempt_token CHAR(36) NOT NULL,
    status SMALLINT NOT NULL,
    aggregate_id CHAR(36) NULL,
    result_json JSON NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (operation_id),
    UNIQUE KEY uk_commerce_behavior_operation_tenant_key (tenant_id, idempotency_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cloudmold_commerce_session (
    session_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    principal_id CHAR(36) NULL,
    channel_code VARCHAR(32) NOT NULL,
    entrypoint_code VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL,
    identity_link_version BIGINT NOT NULL,
    source_system VARCHAR(32) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id VARCHAR(128) NOT NULL,
    started_at DATETIME(6) NOT NULL,
    last_activity_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (session_id),
    UNIQUE KEY uk_commerce_session_tenant_id (tenant_id, session_id),
    KEY idx_commerce_session_principal_time (tenant_id, principal_id, last_activity_at),
    KEY idx_commerce_session_status_time (tenant_id, status, last_activity_at),
    CONSTRAINT chk_commerce_session_status CHECK (status IN ('ACTIVE', 'CHECKOUT_IN_PROGRESS', 'ABANDONED', 'EXPIRED')),
    CONSTRAINT chk_commerce_session_version CHECK (version > 0),
    CONSTRAINT chk_commerce_session_identity_link_version CHECK (identity_link_version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cloudmold_commerce_session_identity_link (
    link_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    session_id CHAR(36) NOT NULL,
    principal_id CHAR(36) NOT NULL,
    link_version BIGINT NOT NULL,
    session_version BIGINT NOT NULL,
    source_system VARCHAR(32) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id VARCHAR(128) NOT NULL,
    linked_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (link_id),
    UNIQUE KEY uk_commerce_session_identity_version (tenant_id, session_id, link_version),
    KEY idx_commerce_session_identity_principal_time (tenant_id, principal_id, linked_at),
    CONSTRAINT chk_commerce_session_identity_link_link_version CHECK (link_version > 0),
    CONSTRAINT chk_commerce_session_identity_session_version CHECK (session_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cloudmold_commerce_behavior_event (
    behavior_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    session_id CHAR(36) NOT NULL,
    session_version BIGINT NOT NULL,
    behavior_type VARCHAR(32) NOT NULL,
    principal_id CHAR(36) NULL,
    canonical_spu_id CHAR(36) NULL,
    sku_id CHAR(36) NULL,
    search_token VARCHAR(128) NULL,
    result_set_token VARCHAR(128) NULL,
    result_position INT NULL,
    quantity INT NULL,
    checkout_token VARCHAR(128) NULL,
    source_system VARCHAR(32) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id VARCHAR(128) NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (behavior_id),
    UNIQUE KEY uk_commerce_behavior_event_tenant_id (tenant_id, behavior_id),
    KEY idx_commerce_behavior_session_time (tenant_id, session_id, occurred_at),
    KEY idx_commerce_behavior_principal_time (tenant_id, principal_id, occurred_at),
    KEY idx_commerce_behavior_spu_time (tenant_id, canonical_spu_id, occurred_at),
    CONSTRAINT chk_commerce_behavior_type CHECK (behavior_type IN (
        'PDP_VIEWED', 'SEARCH_REQUESTED', 'SEARCH_RESULT_EXPOSED', 'SEARCH_RESULT_CLICKED',
        'CART_ADDED', 'CART_REMOVED', 'CHECKOUT_STARTED', 'CHECKOUT_ABANDONED'
    )),
    CONSTRAINT chk_commerce_behavior_session_version CHECK (session_version > 0),
    CONSTRAINT chk_commerce_behavior_result_position CHECK (result_position IS NULL OR result_position >= 0),
    CONSTRAINT chk_commerce_behavior_quantity CHECK (quantity IS NULL OR quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cloudmold_commerce_session_payment_attribution (
    attribution_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    session_id CHAR(36) NOT NULL,
    session_version BIGINT NOT NULL,
    principal_id CHAR(36) NOT NULL,
    checkout_token VARCHAR(128) NOT NULL,
    order_id CHAR(36) NOT NULL,
    order_version BIGINT NOT NULL,
    payment_id CHAR(36) NOT NULL,
    shop_id CHAR(36) NULL,
    channel_code VARCHAR(32) NULL,
    source_system VARCHAR(32) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id VARCHAR(128) NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (attribution_id),
    UNIQUE KEY uk_commerce_payment_attribution_session_order (tenant_id, session_id, order_id),
    UNIQUE KEY uk_commerce_payment_attribution_payment (tenant_id, payment_id),
    KEY idx_commerce_payment_attribution_principal_time (tenant_id, principal_id, occurred_at),
    KEY idx_commerce_payment_attribution_shop_time (tenant_id, shop_id, occurred_at),
    CONSTRAINT chk_commerce_payment_attribution_session_version CHECK (session_version > 0),
    CONSTRAINT chk_commerce_payment_attribution_order_version CHECK (order_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
