package cn.iocoder.yudao.module.cloudmold.quality.api;

public enum QualityOperation {
    CREATE_STANDARD,
    PUBLISH_STANDARD,
    CERTIFY_AUTHENTICATOR,
    REVOKE_AUTHENTICATOR,
    CREATE_INSPECTION_TASK,
    ASSIGN_INSPECTION_TASK,
    START_INSPECTION_TASK,
    DECIDE_INSPECTION_TASK,
    REQUEST_RECHECK,
    ASSIGN_RECHECK_REVIEWER,
    SUBMIT_RECHECK_DECISION,
    ADJUDICATE_INSPECTION_TASK,
    COMPLETE_INSPECTION_TASK,
    OPEN_CAPA,
    RESOLVE_CAPA,
    OPEN_RECALL_ACTION,
    ACKNOWLEDGE_RECALL_ACTION,
    RESOLVE_RECALL_ACTION
}
