package cn.iocoder.yudao.module.cloudmold.procurement.service.query;

import cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder;
import cn.iocoder.yudao.module.cloudmold.procurement.controller.admin.vo.ProcurementAdminVo.*;
import cn.iocoder.yudao.module.cloudmold.procurement.dal.dataobject.ProcurementAdminRecords.*;
import cn.iocoder.yudao.module.cloudmold.procurement.dal.dataobject.ProcurementRecords.*;
import cn.iocoder.yudao.module.cloudmold.procurement.dal.dataobject.ProcurementSourcingRecords.*;
import cn.iocoder.yudao.module.cloudmold.procurement.dal.mysql.ProcurementMapper;
import cn.iocoder.yudao.module.cloudmold.procurement.dal.mysql.ProcurementSourcingMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.temporal.TemporalAccessor;
import java.util.*;
import java.util.function.Function;

@Service @RequiredArgsConstructor
public class ProcurementAdminQueryService {
    private final ProcurementMapper procurement; private final ProcurementSourcingMapper sourcing;

    public Page<RequisitionPageItem> requisitions(int no,int size,String status,String keyword){long t=tenant();return page(procurement.countPurchaseRequisitionPage(t,status,keyword),procurement.selectRequisitionAdminPage(t,status,keyword,offset(no,size),size).stream().map(x->new RequisitionPageItem().setAggregateVersion(x.getAggregateVersion()).setApprovedAt(time(x.getApprovedAt())).setLineCount(x.getLineCount()).setRequisitionCode(x.getRequisitionCode()).setRequisitionId(x.getRequisitionId()).setRequestedByPrincipalId(x.getRequestedByPrincipalId()).setRequiredDeliveryDate(time(x.getRequiredDeliveryDate())).setStatus(x.getStatus()).setSubmittedAt(time(x.getSubmittedAt())).setTotalRequestedQuantity(dec(x.getTotalRequestedQuantity())).setUomCode(x.getUomCode()).setUpdatedAt(time(x.getUpdatedAt()))).toList());}
    public Page<RfqPageItem> events(int no,int size,String status,String keyword){long t=tenant();return page(sourcing.countEventPage(t,status,keyword),sourcing.selectRfqAdminPage(t,status,keyword,offset(no,size),size).stream().map(x->new RfqPageItem().setAggregateVersion(x.getAggregateVersion()).setEventCode(x.getEventCode()).setEventId(x.getEventId()).setInvitationCount(x.getInvitationCount()).setLineCount(x.getLineCount()).setQuotationDeadline(time(x.getQuotationDeadline())).setQuotationRevisionCount(x.getQuotationRevisionCount()).setRequisitionCode(x.getRequisitionCode()).setRequisitionId(x.getRequisitionId()).setStatus(x.getStatus()).setTitle(x.getTitle()).setUpdatedAt(time(x.getUpdatedAt()))).toList());}
    public Page<QuotationPageItem> quotations(int no,int size,String keyword){long t=tenant();return page(sourcing.countQuotationPage(t,keyword),sourcing.selectQuotationAdminPage(t,keyword,offset(no,size),size).stream().map(x->new QuotationPageItem().setAggregateVersion(x.getAggregateVersion()).setCurrencyCode(x.getCurrencyCode()).setEventCode(x.getEventCode()).setEventId(x.getEventId()).setGrossAmountMinor(str(x.getGrossAmountMinor())).setLineCount(x.getLineCount()).setQuotationCode(x.getQuotationCode()).setQuotationId(x.getQuotationId()).setRevisionNumber(x.getRevisionNumber()).setStatus(x.getStatus()).setSupplierId(x.getSupplierId()).setSubmittedAt(time(x.getSubmittedAt())).setUpdatedAt(time(x.getUpdatedAt()))).toList());}
    public Page<AwardPageItem> awards(int no,int size,String status,String keyword){long t=tenant();return page(sourcing.countAwardPage(t,status,keyword),sourcing.selectAwardAdminPage(t,status,keyword,offset(no,size),size).stream().map(this::awardPage).toList());}
    public Page<PurchaseOrderPageItem> orders(int no,int size,String status,String keyword){long t=tenant();return page(procurement.countOrderPage(t,status,keyword),procurement.selectOrderAdminPage(t,status,keyword,offset(no,size),size).stream().map(this::orderPage).toList());}

    public AwardDetail award(String id){long t=tenant();Award a=required(sourcing.selectAward(t,id),"award not found");SourcingEvent e=required(sourcing.selectEvent(t,a.getEventId()),"sourcing event not found");EvaluationPolicy p=required(sourcing.selectPolicy(t,e.getEventId(),a.getPolicyId()),"evaluation policy not found");
        List<cn.iocoder.yudao.module.cloudmold.procurement.dal.dataobject.ProcurementSourcingRecords.AwardLine> raw=sourcing.selectAwardLines(t,id); AwardSummary summary=new AwardSummary().setAggregateVersion(a.getVersion()).setAwardCode(a.getAwardCode()).setAwardId(a.getAwardId()).setAwardedQuantity(raw.stream().map(cn.iocoder.yudao.module.cloudmold.procurement.dal.dataobject.ProcurementSourcingRecords.AwardLine::getAwardedQuantity).reduce(BigDecimal.ZERO,BigDecimal::add)).setEventAggregateVersion(e.getVersion()).setEventCode(e.getEventCode()).setEventId(e.getEventId()).setLineCount(raw.size()).setPurchaseOrderCount(0).setStatus(a.getStatus()).setSupplierCount((int)raw.stream().map(cn.iocoder.yudao.module.cloudmold.procurement.dal.dataobject.ProcurementSourcingRecords.AwardLine::getSupplierId).distinct().count()).setUpdatedAt(a.getUpdatedAt());
        AwardPageItem base=awardPage(summary); AwardDetail d=new AwardDetail(); copyAward(base,d); d.setApprovedAt(time(a.getApprovedAt())).setApprovedGrossAmountMinor(str(sumLong(raw,cn.iocoder.yudao.module.cloudmold.procurement.dal.dataobject.ProcurementSourcingRecords.AwardLine::getLineGrossAmountMinor))).setAwardedNetAmountMinor(str(sumLong(raw,cn.iocoder.yudao.module.cloudmold.procurement.dal.dataobject.ProcurementSourcingRecords.AwardLine::getLineNetAmountMinor))).setAwardedTaxAmountMinor(str(sumLong(raw,cn.iocoder.yudao.module.cloudmold.procurement.dal.dataobject.ProcurementSourcingRecords.AwardLine::getLineTaxAmountMinor))).setCurrencyCode(raw.isEmpty()?null:raw.get(0).getCurrencyCode()).setDecisionReasonCode(a.getDecisionReasonCode()).setQuotationDeadline(time(e.getQuotationDeadline())).setReviewPolicyCode(p.getPolicyCode()).setSubmittedAt(time(a.getSubmittedAt())).setStatusHistory(history(sourcing.selectAwardHistory(t,id))).setLines(sourcing.selectAwardAdminLines(t,id).stream().map(x->new cn.iocoder.yudao.module.cloudmold.procurement.controller.admin.vo.ProcurementAdminVo.AwardLine().setAwardLineId(x.getAwardLineId()).setAwardedGrossAmountMinor(str(x.getAwardedGrossAmountMinor())).setAwardedQuantity(dec(x.getAwardedQuantity())).setCanonicalSkuId(x.getCanonicalSkuId()).setLineNumber(x.getLineNumber()).setPromisedDeliveryDate(time(x.getPromisedDeliveryDate())).setQuotationId(x.getQuotationId()).setQuotationLineId(x.getQuotationLineId()).setQuotationRevisionNumber(x.getQuotationRevisionNumber()).setRequisitionLineId(x.getRequisitionLineId()).setScore(score(x.getScore())).setSourcingLineId(x.getSourcingLineId()).setSupplierId(x.getSupplierId()).setUnitNetPriceMinor(dec(x.getUnitNetPriceMinor())).setUomCode(x.getUomCode()).setLineage(new Lineage().setAwardId(id).setAwardLineId(x.getAwardLineId()).setQuotationId(x.getQuotationId()).setQuotationLineId(x.getQuotationLineId()).setRequisitionId(x.getRequisitionId()).setRequisitionLineId(x.getRequisitionLineId()).setRequisitionScheduleId(x.getRequisitionScheduleId()).setSourcingEventId(e.getEventId()).setSourcingLineId(x.getSourcingLineId()))).toList()); return d;}

    public PurchaseOrderDetail order(String id){long t=tenant();ProcurementOrder o=required(procurement.selectCurrentHeader(t,id),"procurement order not found"); List<PurchaseOrderItem> items=procurement.selectItems(t,id);List<PurchaseOrderDeliverySchedule> schedules=procurement.selectSchedules(t,id);Map<String,List<PurchaseOrderDeliverySchedule>> byItem=new LinkedHashMap<>();schedules.forEach(s->byItem.computeIfAbsent(s.getItemId(),ignored->new ArrayList<>()).add(s));
        OrderSummary summary=new OrderSummary().setAggregateVersion(o.getVersion()).setAwardId(o.getAwardId()).setCurrencyCode(o.getCurrencyCode()).setGrossAmountMinor(o.getHeaderGrossAmountMinor()).setLineCount(items.size()).setOrderCode(o.getOrderCode()).setOrderId(o.getOrderId()).setOrderedQuantity(items.stream().map(PurchaseOrderItem::getOrderedQuantity).reduce(BigDecimal.ZERO,BigDecimal::add)).setQualifiedQuantity(BigDecimal.ZERO).setReceivedQuantity(BigDecimal.ZERO).setScheduleCount(schedules.size()).setStatus(o.getStatus()).setSupplierId(o.getSupplierId()).setUpdatedAt(o.getUpdatedAt());
        PurchaseOrderPageItem base=orderPage(summary);PurchaseOrderDetail d=new PurchaseOrderDetail();copyOrder(base,d);d.setHeaderNetAmountMinor(str(o.getHeaderNetAmountMinor())).setHeaderTaxAmountMinor(str(o.getHeaderTaxAmountMinor())).setIssuedAt(time(o.getReleasedAt())).setLegalEntityId(o.getLegalEntityId()).setSourceBusinessRef(o.getSourceBusinessRef()).setSourceBusinessType(o.getSourceBusinessType()).setSupplierAcknowledgedAt(time(o.getSupplierConfirmedAt())).setStatusHistory(historyOrder(procurement.selectOrderStatusHistory(t,id))).setLines(items.stream().map(x->new PurchaseOrderLine().setCanonicalSkuId(x.getCanonicalSkuId()).setInvoicedQuantity("0").setItemId(x.getItemId()).setLineGrossAmountMinor(str(x.getLineGrossAmountMinor())).setLineNetAmountMinor(str(x.getLineNetAmountMinor())).setLineNumber(x.getLineNumber()).setLineTaxAmountMinor(str(x.getLineTaxAmountMinor())).setOrderedQuantity(dec(x.getOrderedQuantity())).setQualifiedQuantity("0").setReceivedQuantity("0").setReturnedQuantity("0").setTaxCode(x.getTaxCode()).setTaxRateBps(x.getTaxRateBps()).setUnitNetPriceMinor(dec(x.getUnitNetPriceMinor())).setUomCode(x.getUomCode()).setValuationPolicyId(x.getValuationPolicyId()).setValuationPolicyVersion(x.getValuationPolicyVersion()).setValuationPolicyHash(x.getValuationPolicyHash()).setSchedules(byItem.getOrDefault(x.getItemId(),List.of()).stream().map(s->new PurchaseOrderSchedule().setCanonicalWarehouseId(s.getCanonicalWarehouseId()).setQualifiedQuantity("0").setReceivedQuantity("0").setRequiredDeliveryDate(time(s.getRequiredDeliveryDate())).setScheduleId(s.getScheduleId()).setScheduleNumber(s.getScheduleNumber()).setScheduledQuantity(dec(s.getScheduledQuantity()))).toList()).setLineage(lineage(t,o,x))).toList());return d;}

    private Lineage lineage(long t,ProcurementOrder o,PurchaseOrderItem item){Lineage l=new Lineage().setPurchaseOrderId(o.getOrderId()).setPurchaseOrderItemId(item.getItemId()).setAwardId(o.getAwardId()).setAwardLineId(item.getAwardLineId());if(item.getAwardLineId()!=null){var al=sourcing.selectAwardLines(t,o.getAwardId()).stream().filter(x->item.getAwardLineId().equals(x.getAwardLineId())).findFirst().orElse(null);if(al!=null){var detail=sourcing.selectAwardAdminLines(t,o.getAwardId()).stream().filter(x->item.getAwardLineId().equals(x.getAwardLineId())).findFirst().orElse(null);if(detail!=null)l.setQuotationId(detail.getQuotationId()).setQuotationLineId(detail.getQuotationLineId()).setRequisitionId(detail.getRequisitionId()).setRequisitionLineId(detail.getRequisitionLineId()).setRequisitionScheduleId(detail.getRequisitionScheduleId()).setSourcingLineId(detail.getSourcingLineId());}}return l;}
    private AwardPageItem awardPage(AwardSummary x){return new AwardPageItem().setAggregateVersion(x.getAggregateVersion()).setAwardCode(x.getAwardCode()).setAwardId(x.getAwardId()).setAwardedQuantity(dec(x.getAwardedQuantity())).setEventAggregateVersion(x.getEventAggregateVersion()).setEventCode(x.getEventCode()).setEventId(x.getEventId()).setLineCount(x.getLineCount()).setPurchaseOrderCount(x.getPurchaseOrderCount()).setStatus(x.getStatus()).setSupplierCount(x.getSupplierCount()).setUpdatedAt(time(x.getUpdatedAt()));}
    private PurchaseOrderPageItem orderPage(OrderSummary x){return new PurchaseOrderPageItem().setAggregateVersion(x.getAggregateVersion()).setAwardCode(x.getAwardCode()).setAwardId(x.getAwardId()).setCurrencyCode(x.getCurrencyCode()).setGrossAmountMinor(str(x.getGrossAmountMinor())).setLineCount(x.getLineCount()).setOrderCode(x.getOrderCode()).setOrderId(x.getOrderId()).setOrderedQuantity(dec(x.getOrderedQuantity())).setQualifiedQuantity(dec(x.getQualifiedQuantity())).setReceivedQuantity(dec(x.getReceivedQuantity())).setScheduleCount(x.getScheduleCount()).setStatus(x.getStatus()).setSupplierId(x.getSupplierId()).setUpdatedAt(time(x.getUpdatedAt()));}
    private static List<StatusHistory> history(List<AwardHistory> rows){String[] prev={null};return rows.stream().map(x->{StatusHistory h=new StatusHistory().setActorPrincipalId(x.getActorPrincipalId()).setChangedAt(time(x.getOccurredAt())).setFromStatus(prev[0]).setReasonCode(x.getReasonCode()).setStatusVersion(x.getAggregateVersion()).setToStatus(x.getStatus());prev[0]=x.getStatus();return h;}).toList();}
    private static List<StatusHistory> historyOrder(List<OrderStatusHistory> rows){String[] prev={null};return rows.stream().map(x->{StatusHistory h=new StatusHistory().setActorPrincipalId(x.getActorPrincipalId()).setChangedAt(time(x.getOccurredAt())).setFromStatus(prev[0]).setReasonCode(x.getReasonCode()).setStatusVersion(x.getAggregateVersion()).setToStatus(x.getStatus());prev[0]=x.getStatus();return h;}).toList();}
    private static <T>Page<T> page(long total,List<T> list){return new Page<T>().setTotal(String.valueOf(total)).setList(list);} private static long tenant(){return TenantContextHolder.getRequiredTenantId();} private static long offset(int no,int size){if(no<1||size<1||size>200)throw new IllegalArgumentException("pageNo/pageSize out of range");return (long)(no-1)*size;} private static String str(Object x){return x==null?null:String.valueOf(x);}private static String dec(BigDecimal x){return x==null?null:x.toPlainString();}private static String time(TemporalAccessor x){return x==null?null:x.toString();}private static String score(Integer bps){return bps==null?null:BigDecimal.valueOf(bps).movePointLeft(2).stripTrailingZeros().toPlainString();}private static long sumLong(List<cn.iocoder.yudao.module.cloudmold.procurement.dal.dataobject.ProcurementSourcingRecords.AwardLine> xs,Function<cn.iocoder.yudao.module.cloudmold.procurement.dal.dataobject.ProcurementSourcingRecords.AwardLine,Long> f){return xs.stream().map(f).filter(Objects::nonNull).mapToLong(Long::longValue).sum();}private static<T>T required(T x,String m){if(x==null)throw new IllegalArgumentException(m);return x;}
    private static void copyAward(AwardPageItem s,AwardPageItem d){d.setAggregateVersion(s.getAggregateVersion()).setAwardCode(s.getAwardCode()).setAwardId(s.getAwardId()).setAwardedQuantity(s.getAwardedQuantity()).setEventAggregateVersion(s.getEventAggregateVersion()).setEventCode(s.getEventCode()).setEventId(s.getEventId()).setLineCount(s.getLineCount()).setPurchaseOrderCount(s.getPurchaseOrderCount()).setStatus(s.getStatus()).setSupplierCount(s.getSupplierCount()).setUpdatedAt(s.getUpdatedAt());}
    private static void copyOrder(PurchaseOrderPageItem s,PurchaseOrderPageItem d){d.setAggregateVersion(s.getAggregateVersion()).setAwardCode(s.getAwardCode()).setAwardId(s.getAwardId()).setCurrencyCode(s.getCurrencyCode()).setGrossAmountMinor(s.getGrossAmountMinor()).setLineCount(s.getLineCount()).setOrderCode(s.getOrderCode()).setOrderId(s.getOrderId()).setOrderedQuantity(s.getOrderedQuantity()).setQualifiedQuantity(s.getQualifiedQuantity()).setReceivedQuantity(s.getReceivedQuantity()).setScheduleCount(s.getScheduleCount()).setStatus(s.getStatus()).setSupplierId(s.getSupplierId()).setUpdatedAt(s.getUpdatedAt());}
}
