package cn.iocoder.yudao.module.cloudmold.procurement.api;

public enum SourcingOperation {
    CREATE_SOURCING_EVENT,
    PUBLISH_SOURCING_EVENT,
    INVITE_SUPPLIER,
    OPEN_QUOTING,
    SUBMIT_QUOTATION_REVISION,
    WITHDRAW_QUOTATION_REVISION,
    CLOSE_QUOTING,
    CREATE_EVALUATION_POLICY,
    RECORD_EVALUATION_SCORE,
    CREATE_AWARD_DRAFT,
    SUBMIT_AWARD,
    APPROVE_AWARD,
    REJECT_AWARD,
    CLOSE_SOURCING_EVENT,
    CANCEL_SOURCING_EVENT
}
